project:
  type: website

website:
  title: "MAT 186: Data Science Labs"
  # Place the footer here, inside the website section
  page-footer:
    left: "Â© 2026 MAT 186 | Dutchess Community College"
    center: "Last updated: {{< meta date-modified >}}"
    right: "Designed for Accessibility"
  sidebar:
    contents:
      - index.md
      - labs/lab1.md

format:
  html:
    theme: [cosmo, style.css]
    # Place the date settings here, inside the html format section
    date-modified: last-modified
    date-format: "MMMM D, YYYY"
    toc: true
