project:
  type: website

execute:
  warning: false
  message: false

website:
  title: "MAT 186: Data Science"
  
  # Navbar Logo (Top Left)
  navbar:
    logo: "images/dcc-logo.png"
    logo-height: "20px"
    logo-alt: "Dutchess Community College Logo" # Required for accessibility
    search: true  # This activates the search bar
    background: "#002147" # DCC Navy Blue
    left:
      - href: index.qmd
        text: Home

  # Sidebar Navigation (Matches your 17 Labs)
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Course Labs"
        contents:
          - text: "Lab 1: R and RStudio Installation"
            file: labs/lab01.qmd
          - text: "Lab 2: RStudio Project and Quarto Documents"
            file: labs/lab02.qmd
          - text: "Lab 3: Mathematical Notation in Quarto"
            file: labs/lab03.qmd
          - text: "Lab 4: GitHub Repository"
            file: labs/lab04.qmd
          - text: "Lab 5: Getting data into R"
            file: labs/lab05.qmd
          - text: "Lab 6: Data collection"
            file: labs/lab06.qmd
          - text: "Lab 7: Cleaning Data"
            file: labs/lab07.qmd
          - text: "Lab 8: Exploratory Data Analysis"
            file: labs/lab08.qmd
          - text: "Lab 9: Probability distribution"
            file: labs/lab09.qmd
          - text: "Lab 10: Statistical inference for one mean"
            file: labs/lab10.qmd
          - text: "Lab 11: Statistical inference for one proportion"
            file: labs/lab11.qmd
          - text: "Lab 12: Statistical inference for two means"
            file: labs/lab12.qmd
          - text: "Lab 13: Statistical inference for two proportions"
            file: labs/lab13.qmd
          - text: "Lab 14: Bootstrapping"
            file: labs/lab14.qmd
          - text: "Lab 15: Non-parametric methods"
            file: labs/lab15.qmd
          - text: "Lab 16: Analysis of variance (ANOVA)"
            file: labs/lab16.qmd
          - text: "Lab 17: Regression models"
            file: labs/lab17_F26.qmd

  # Page Footer (Bottom)

  page-footer:
    left: |
      ![](images/dcc-logo.png){width=50px fig-alt="DCC Logo"}  
      **Dutchess Community College**
    center: "Last updated: {{< meta date-modified >}}"
    right: |
      [Accessibility Statement](/accessibility.qmd)

format:
  html:
    html-math-method: mathjax
    theme: cosmo
    css: style.css        # Use 'css:' instead of putting it inside brackets
    date-modified: last-modified
    date-format: "MMMM D, YYYY"
    toc: true
    toc-location: right
