project:
  type: website

website:
  title: "MAT 186: Data Science"
  
 



  # ADD THIS SECTION: This is what makes the labs visible!
  sidebar:
    style: "docked"
    contents:
      - index.md
      - section: "Labs"
        contents:
          - labs/lab01.md   # Check: is it .md or .qmd?
          - labs/lab02.md
          - labs/lab03.md
          - labs/lab4.md
          - labs/lab05.md
          - labs/lab06.md
          - labs/lab07.md
          - labs/lab08.md
          - labs/lab09.md
          - labs/lab10.md
          - labs/lab11.md
          - labs/lab12.md
          - labs/lab13.md
          - labs/lab14.md
          - labs/lab15.md
          - labs/lab16.md
          - labs/la17.md
          - labs/lab18.md



 

format:
  html:
    theme: [cosmo, style.css]
    date-modified: last-modified
    date-format: "MMMM D, YYYY"
    toc: true
