project:
  type: website

website:
  title: "MAT 186: Data Science Labs"
  sidebar:
    style: "docked"
    background: "#f8f9fa"
    contents:
      - section: "Welcome"
        contents:
          - index.md
      - section: "The Labs"
        contents:
          - labs/lab1.md
          - labs/lab2.md
          - labs/lab8.md
          - labs/lab11.md
          - labs/lab17.md

format:
  html:
    theme: [cosmo, style.css] # Links your CSS file!
    toc: true                # Table of contents for accessibility
    code-copy: true          # Easy for students to copy code




website:
  page-footer:
    left: "Â© 2026 MAT 186 | Dutchess Community College"
    center: "Last updated: {{< meta date-modified >}}"
    right: "Designed for Accessibility"

format:
  html:
    date-modified: last-modified # Tells Quarto to look at when the file was saved
    date-format: "MMMM D, YYYY" # Makes it readable (e.g., January 31, 2026)
