project:
  type: website

website:
  title: "MAT 186: Data Science"
  
 



  # ADD THIS SECTION: This is what makes the labs visible!
  sidebar:
    style: "docked"
    contents:
      - index.md
      - section: "Labs"
        contents:
          - labs/lab1.md   # Check: is it .md or .qmd?
          - labs/lab8.md
          - labs/lab17.md



 

format:
  html:
    theme: [cosmo, style.css]
    date-modified: last-modified
    date-format: "MMMM D, YYYY"
    toc: true
